kind: pipeline 
name: default 
type: docker 
steps:
- name: publish  
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: 301032990450.dkr.ecr.us-east-1.amazonaws.com/drone-ecr
    registry: 301032990450.dkr.ecr.us-east-1.amazonaws.com
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 54.175.238.108
    username: ubuntu
    port: 22
    key:
      from_secret: ssh_key
      script:
        - echo hello
        - echo world
 
